version: '3'
services:
  minecraft-1.19.4-spigot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './var:/mnt/var'
    ports:
      - '25565:25565'
    tty: true
    stdin_open: true